services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-app
    restart: unless-stopped
    volumes:
      - ./ecommerce-api:/var/www/html/
    depends_on:
      - db

  nginx:
    image: nginx:1.19-alpine
    container_name: ecommerce-server
    restart: on-failure
    ports:
      - "8068:80"
    volumes:
      - ./ecommerce-api:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app

  db:
    image: mysql:latest
    container_name: ecommerce-db
    restart: on-failure
    ports:
      - "3314:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
